import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "@/components/Footer";
import TopProgressBar from "@/components/TopProgressBar";
import ClientProviders from "@/components/ClientProviders"; // New client wrapper
import NetworkStatus from "@/components/NetworkStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "SaurabhCodes",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="min-h-screen bg-gradient-to-br from-[#060e1a] via-[#0f1e2d] to-[#1a3248] bg-fixed bg-cover"
      >
        <ClientProviders>
          <TopProgressBar />
          <NetworkStatus />
          <Navbar /> {/* Navbar is a client component */}
          {children}
          <Footer />
        </ClientProviders>
      </body>
    </html>
  );
}
